### ISSUE TITLE
Uncaught TypeError: Cannot read properties of undefined (reading 'inflate')

### ISSUE THREAD

**Issue by habibutsu** [photopea/UPNG.js#88]
```
UPNG.min.js:1 Uncaught TypeError: Cannot read properties of undefined (reading 'inflate')
    at e.decode._inflate (UPNG.min.js:1:5162)
    at e.decode._decompress (UPNG.min.js:1:5009)
    at e.decode (UPNG.min.js:1:4807)
    at <anonymous>:1:6
```

**Comment by photopea** [comment]
Hi, what is UPNG.min.js ?

**Comment by habibutsu** [comment]
I took it from this https://cdnjs.cloudflare.com/ajax/libs/upng-js/2.1.0/UPNG.min.js

**Comment by photopea** [comment]
That was not made by me :/  Could you try using the library from here instead?
