### ISSUE TITLE
How to resolve this issue? Kindly help

### ISSUE THREAD

**Issue by bvibin** [photopea/UPNG.js#90]
UPNG.js:980 Uncaught ReferenceError: pako is not defined
    at _filterZero (UPNG.js:980:80)
    at compressPNG (UPNG.js:764:24)
    at Object.encode (UPNG.js:615:9)
    at img.onload (app.js:18:41)
<img width="779" alt="Screenshot 2024-02-12 at 10 50 55 PM" src="https://github.com/photopea/UPNG.js/assets/108187401/d1a72dd1-9c8a-4e3f-96c1-34d4c4c32cca">

**Comment by bvibin** [comment]
Sorry I missed to include pako.js. I have resolved it. Thank you
